### ISSUE TITLE
[lua] "goto" missing in Lua syntax highlighting

### ISSUE THREAD

**Issue by aeschli** [textmate/lua.tmbundle#5]
_From @BinaryInk on December 2, 2015 22:2_

When using the goto keyword, it is not highlighted, nor is the label selected.

Example:

```
function func()
     if this == that then
          do = this
          goto continueHere
     elseif this2 == that2 then
          ::continueHere::
     end
end
```

Ignoring the terrible example itself, the problem occurs on line 4 where no highlighting will occur. Line 6, where the label is, highlights correctly, however.

_Copied from original issue: Microsoft/vscode#942_

**Comment by infininight** [comment]
Pulled the patch but also added a match for the labels.
