### ISSUE TITLE
Lua function colorizing error

### ISSUE THREAD

**Issue by aeschli** [textmate/lua.tmbundle#7]
_From @actboy168 on September 29, 2016 11:19_
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
![qq 20160929191837](https://cloud.githubusercontent.com/assets/1836844/18951806/9ccdaa6c-8679-11e6-8d53-0301c79b44c0.jpg)

_Copied from original issue: Microsoft/vscode#12994_

**Comment by infininight** [comment]
Corrected, thanks for the note. The identifier match in this location any others to allow numbers except as the starting character.

cc @actboy168 (This has been deployed for TextMate, will be VSCode when they update their copy.)
